# Generated by Django 2.0.4 on 2018-06-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0002_auto_20180606_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
        migrations.AlterField(
            model_name='film',
            name='nazev',
            field=models.CharField(max_length=200, verbose_name='Název Filmu'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rezie',
            field=models.CharField(max_length=180, verbose_name='Režie'),
        ),
        migrations.AlterField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviebook.Zanr', verbose_name='Žánr'),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='nazev_zanru',
            field=models.CharField(max_length=80, verbose_name='Žánr'),
        ),
    ]
