# Generated by Django 2.0.4 on 2020-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0004_auto_20180628_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_akce', models.CharField(max_length=80, verbose_name='Název akce')),
                ('datum_konani', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Akce',
                'verbose_name_plural': 'Akce',
            },
        ),
    ]
