# Generated by Django 2.0.4 on 2020-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0005_akce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('rc', models.CharField(default='', max_length=10, unique=True, verbose_name='Rodné Císlo')),
                ('narozen', models.DateTimeField(auto_now_add=True)),
                ('clenem_od', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('jmeno', models.CharField(default='', max_length=40)),
                ('prijmeni', models.CharField(default='', max_length=40)),
                ('facr_id', models.IntegerField(default=1)),
                ('var_symbol', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Clen',
                'verbose_name_plural': 'Clenové',
            },
        ),
    ]
