# Generated by Django 2.0.4 on 2020-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0006_clen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='klub_id',
            field=models.IntegerField(default=1050181),
        ),
    ]
