# Generated by Django 2.0.4 on 2020-10-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0007_clen_klub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucastnici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebook.Akce', verbose_name='Akce')),
                ('clen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebook.Clen', verbose_name='Clen')),
            ],
            options={
                'verbose_name': 'Úcastník',
                'verbose_name_plural': 'Úcastníci',
            },
        ),
    ]
