# Generated by Django 2.0.4 on 2020-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0010_clen_cislo_uctu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akce',
            name='trener',
        ),
        migrations.RemoveField(
            model_name='akce',
            name='vedouci',
        ),
    ]
