# Generated by Django 2.0.4 on 2020-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0012_auto_20201006_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='akce',
            name='vedouci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vedoucip', to='moviebook.Clen', verbose_name='Vedouci'),
        ),
    ]
