# Generated by Django 2.0.4 on 2020-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0014_akce_trener'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='telefonni_cislo',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='clenem_od',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clen',
            name='narozen',
            field=models.DateTimeField(),
        ),
    ]
