# Generated by Django 2.0.4 on 2020-10-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0015_auto_20201006_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='telefonni_cislo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
