# Generated by Django 2.0.4 on 2020-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0016_auto_20201006_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='cislo_uctu',
            field=models.CharField(default='', max_length=30),
        ),
    ]
