# Generated by Django 2.0.4 on 2020-10-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0017_auto_20201006_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clen',
            name='telefonni_cislo',
        ),
    ]
