# Generated by Django 2.0.4 on 2020-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0018_remove_clen_telefonni_cislo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='telefonni_cislo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
