# Generated by Django 2.0.4 on 2020-10-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0019_clen_telefonni_cislo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='prijmeni_rodic',
            field=models.CharField(default='', max_length=40),
        ),
    ]
