# Generated by Django 2.0.4 on 2020-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0021_auto_20201012_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='rok_narozeni',
            field=models.CharField(default='1111', max_length=4),
        ),
    ]
