# Generated by Django 2.0.4 on 2020-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0022_clen_rok_narozeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akce',
            name='datum_konani',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='akce',
            name='nazev_akce',
            field=models.CharField(max_length=80, null=True, verbose_name='Název akce'),
        ),
        migrations.AlterField(
            model_name='clen',
            name='cislo_uctu',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='clenem_od',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='email',
            field=models.EmailField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='facr_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='jmeno',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='klub_id',
            field=models.IntegerField(default=1050181, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='narozen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='prijmeni',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='prijmeni_rodic',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='rc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='rok_narozeni',
            field=models.CharField(default='1111', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='telefonni_cislo',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='typ_clena',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='ucet_kod_banky',
            field=models.CharField(default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='ucet_nazev_protiuctu',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='ucet_protiucet',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='ucet_zprava_pro_prijemce',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='var_symbol',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='naplanovane_platby',
            name='objem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='naplanovane_platby',
            name='popis_platby',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='naplanovane_platby',
            name='sdelelni',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='naplanovane_platby',
            name='splatnost',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='cislo_uctu_prichozi',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='datum',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='kod_banky',
            field=models.CharField(default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='nazev_protiuctu',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='objem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='poznamka',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='protiucet',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='typ_platby',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='prichozi_platby',
            name='zprava_pro_prijemce',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=30, null=True, verbose_name='Tagy'),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='nazev_zanru',
            field=models.CharField(max_length=80, null=True, verbose_name='Žánr'),
        ),
    ]
