# Generated by Django 2.0.4 on 2020-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0023_auto_20201014_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='ucet_poznamka',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
