# Generated by Django 2.0.4 on 2020-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0024_auto_20201014_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='clen',
            name='ucet_protiucet2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
