# Generated by Django 3.1.3 on 2020-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0026_auto_20201123_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='facr_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='klub_id',
            field=models.IntegerField(default=1050181, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='rok_narozeni',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='var_symbol',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
