# Generated by Django 3.1.3 on 2020-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0027_auto_20201123_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='narozen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
