# Generated by Django 3.1.3 on 2020-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0028_auto_20201123_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='facr_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clen',
            name='klub_id',
            field=models.IntegerField(default=1050181),
        ),
        migrations.AlterField(
            model_name='clen',
            name='var_symbol',
            field=models.IntegerField(default=1),
        ),
    ]
