# Generated by Django 3.1.3 on 2020-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0030_auto_20201123_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prichozi_platby',
            name='clen',
            field=models.IntegerField(null=True),
        ),
    ]
