# Generated by Django 3.1.3 on 2020-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0031_auto_20201203_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prichozi_platby',
            name='clen',
        ),
        migrations.AddField(
            model_name='prichozi_platby',
            name='jmeno',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prichozi_platby',
            name='prijmeni',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
