# Generated by Django 3.1.4 on 2020-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0032_auto_20201204_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='narozen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
