# Generated by Django 3.1.4 on 2020-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0033_auto_20201205_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='prichozi_platby',
            name='facr_id',
            field=models.IntegerField(default=1),
        ),
    ]
