# Generated by Django 2.0.4 on 2018-06-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zanr',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviebook.Zanr'),
        ),
    ]
