# Generated by Django 2.0.4 on 2020-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0003_auto_20200927_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='zanr',
        ),
    ]
