# Generated by Django 2.0.4 on 2020-09-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0004_remove_film_zanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviebook.Zanr', verbose_name='Žánr'),
        ),
    ]
