# Generated by Django 3.1.3 on 2020-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAddresList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsageLabel', models.CharField(max_length=80, null=True, verbose_name='Žánr')),
                ('UsageCode', models.IntegerField(default=1, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UsageLabel',
                'verbose_name_plural': 'UsageLabels',
            },
        ),
    ]
